name: Chocolatine

on:
  push:
    branches-ignore:
    - "ga-ignore-*"
  pull_request:
    branches-ignore:
    - "ga-ignore-*"

env:
  MIRROR_URL: git@github.com:EpitechPromo2027/B-DOP-200-NAN-2-1-chocolatine-nicolas2.bertrand.git
  EXECUTABLES: "chocolatine"

jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run coding style checker
        run: check.sh $(pwd) $(pwd)
      - name: Coding style errors display
        run: |
          CSR_CONTENT=$(check.sh $(pwd) $(pwd) 2>&1)
          if [[ -n $CSR_CONTENT ]]; then
            while read -r ERRORS; do
              array=($ERRORS)
              echo "::error file=${array[1]#./},title=${array[3]#./}::${array[4]#./}"
            done <<< "$CSR_CONTENT"
            echo "Coding style errors detected"
            exit 1
          else
            echo "No coding style errors"
          fi

  check_program_compilation:
    runs-on: ubuntu-latest  
    container:
      image: epitechcontent/epitest-docker
    needs: check_coding_style
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Launch make
        run: make
        timeout-minutes: 2
      - name: Clean the build directory
        run: make clean
      - name: Check executables
        run: |
          for executable in $(echo "${EXECUTABLES}" | tr ',' ' '); do
            if [ ! -x "${executable}" ]; then
              echo "Error: ${executable} is not executable or does not exist"
              exit 1
            fi
          done

  run_tests:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker
    needs: check_program_compilation
    timeout-minutes: 2
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Launch tests
      run: make tests_run

  push_to_mirror:
    runs-on: ubuntu-latest
    needs: [check_coding_style, check_program_compilation, run_tests]
    if: github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Push to mirror
        uses: pixta-dev/repository-mirroring-action@v1.1.1
        with:
          target_repo_url: ${{ env.MIRROR_URL}}
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}